export const tableData = [
  {
    topic: 'Algebra Basics',
    subject: 'Math',
    classYear: 'Grade 10',
    totalNotes: 12,
    lastNoteAdded: '2025-08-01',
  },
  {
    topic: 'World History',
    subject: 'History',
    classYear: 'Grade 9',
    totalNotes: 8,
    lastNoteAdded: '2025-07-28',
  },
  {
    topic: 'Organic Chemistry',
    subject: 'Science',
    classYear: 'Grade 12',
    totalNotes: 15,
    lastNoteAdded: '2025-07-30',
  },
  {
    topic: 'Calculus I',
    subject: 'Math',
    classYear: 'BSc',
    totalNotes: 20,
    lastNoteAdded: '2025-07-25',
  },
  {
    topic: 'Modern Physics',
    subject: 'Science',
    classYear: 'BSc',
    totalNotes: 10,
    lastNoteAdded: '2025-07-22',
  },
  {
    topic: 'British Literature',
    subject: 'History',
    classYear: 'Grade 11',
    totalNotes: 7,
    lastNoteAdded: '2025-07-20',
  },
  {
    topic: 'Geometry Essentials',
    subject: 'Math',
    classYear: 'Grade 8',
    totalNotes: 9,
    lastNoteAdded: '2025-07-18',
  },
  {
    topic: 'Ancient Civilizations',
    subject: 'History',
    classYear: 'Grade 7',
    totalNotes: 6,
    lastNoteAdded: '2025-07-15',
  },
  {
    topic: 'Physics Lab',
    subject: 'Science',
    classYear: 'Grade 10',
    totalNotes: 11,
    lastNoteAdded: '2025-07-12',
  },
  {
    topic: 'Trigonometry',
    subject: 'Math',
    classYear: 'Grade 11',
    totalNotes: 13,
    lastNoteAdded: '2025-07-10',
  },
];