export const tableData = [
  {
    topic: 'Algebra Basics',
    subject: 'Math',
    classYear: 'Grade 10',
    totalNotes: 12,
    lastNoteAdded: '3 min ago',
  },
  {
    topic: 'World History',
    subject: 'History',
    classYear: 'Grade 9',
    totalNotes: 8,
    lastNoteAdded: '15 min ago',
  },
  {
    topic: 'Organic Chemistry',
    subject: 'Science',
    classYear: 'Grade 12',
    totalNotes: 15,
    lastNoteAdded: '1 hour ago',
  },
  {
    topic: 'Calculus I',
    subject: 'Math',
    classYear: 'BSc',
    totalNotes: 20,
    lastNoteAdded: '2 hours ago',
  },
  {
    topic: 'Modern Physics',
    subject: 'Science',
    classYear: 'BSc',
    totalNotes: 10,
    lastNoteAdded: '5 hours ago',
  },
  {
    topic: 'British Literature',
    subject: 'History',
    classYear: 'Grade 11',
    totalNotes: 7,
    lastNoteAdded: '1 day ago',
  },
  {
    topic: 'Geometry Essentials',
    subject: 'Math',
    classYear: 'Grade 8',
    totalNotes: 9,
    lastNoteAdded: '2 days ago',
  },
  {
    topic: 'Ancient Civilizations',
    subject: 'History',
    classYear: 'Grade 7',
    totalNotes: 6,
    lastNoteAdded: '3 days ago',
  },
  {
    topic: 'Physics Lab',
    subject: 'Science',
    classYear: 'Grade 10',
    totalNotes: 11,
    lastNoteAdded: '5 days ago',
  },
  {
    topic: 'Trigonometry',
    subject: 'Math',
    classYear: 'Grade 11',
    totalNotes: 13,
    lastNoteAdded: '1 week ago',
  },
];

export const topicTableData = [
  {
    fileName: 'Algebra_Basics.pdf',
    rating: 4.5,
    feedbacks: 12,
    uploadedBy: 'John Doe',
    uploadDate: '1 August, 2025',
  },
  {
    fileName: 'World_History.pdf',
    rating: 4.2,
    feedbacks: 8,
    uploadedBy: 'Jane Smith',
    uploadDate: '28 July, 2025',
  },
  {
    fileName: 'Organic_Chemistry.pdf',
    rating: 4.8,
    feedbacks: 15,
    uploadedBy: 'Alice Brown',
    uploadDate: '30 July, 2025',
  },
  {
    fileName: 'Calculus_I.pdf',
    rating: 4.1,
    feedbacks: 20,
    uploadedBy: 'Bob Lee',
    uploadDate: '25 July, 2025',
  },
  {
    fileName: 'Modern_Physics.pdf',
    rating: 4.7,
    feedbacks: 10,
    uploadedBy: 'Charlie Kim',
    uploadDate: '22 July, 2025',
  },
  {
    fileName: 'British_Literature.pdf',
    rating: 4.0,
    feedbacks: 7,
    uploadedBy: 'Diana Green',
    uploadDate: '20 July, 2025',
  },
  {
    fileName: 'Geometry_Essentials.pdf',
    rating: 4.3,
    feedbacks: 9,
    uploadedBy: 'Evan White',
    uploadDate: '18 July, 2025',
  },
  {
    fileName: 'Ancient_Civilizations.pdf',
    rating: 4.6,
    feedbacks: 6,
    uploadedBy: 'Fiona Black',
    uploadDate: '15 July, 2025',
  },
  {
    fileName: 'Physics_Lab.pdf',
    rating: 4.4,
    feedbacks: 11,
    uploadedBy: 'George Brown',
    uploadDate: '12 July, 2025',
  },
  {
    fileName: 'Trigonometry.pdf',
    rating: 4.9,
    feedbacks: 13,
    uploadedBy: 'Helen Clark',
    uploadDate: '10 July, 2025',
  },
];
