export const tableData = [
  {
    topic: 'Algebra Basics',
    subject: 'Math',
    classYear: 'Grade 10',
    totalNotes: 12,
    lastNoteAdded: '3 min ago',
  },
  {
    topic: 'World History',
    subject: 'History',
    classYear: 'Grade 9',
    totalNotes: 8,
    lastNoteAdded: '15 min ago',
  },
  {
    topic: 'Organic Chemistry',
    subject: 'Science',
    classYear: 'Grade 12',
    totalNotes: 15,
    lastNoteAdded: '1 hour ago',
  },
  {
    topic: 'Calculus I',
    subject: 'Math',
    classYear: 'BSc',
    totalNotes: 20,
    lastNoteAdded: '2 hours ago',
  },
  {
    topic: 'Modern Physics',
    subject: 'Science',
    classYear: 'BSc',
    totalNotes: 10,
    lastNoteAdded: '5 hours ago',
  },
  {
    topic: 'British Literature',
    subject: 'History',
    classYear: 'Grade 11',
    totalNotes: 7,
    lastNoteAdded: '1 day ago',
  },
  {
    topic: 'Geometry Essentials',
    subject: 'Math',
    classYear: 'Grade 8',
    totalNotes: 9,
    lastNoteAdded: '2 days ago',
  },
  {
    topic: 'Ancient Civilizations',
    subject: 'History',
    classYear: 'Grade 7',
    totalNotes: 6,
    lastNoteAdded: '3 days ago',
  },
  {
    topic: 'Physics Lab',
    subject: 'Science',
    classYear: 'Grade 10',
    totalNotes: 11,
    lastNoteAdded: '5 days ago',
  },
  {
    topic: 'Trigonometry',
    subject: 'Math',
    classYear: 'Grade 11',
    totalNotes: 13,
    lastNoteAdded: '1 week ago',
  },
];